---
- name: Stop services
  ansible.builtin.systemd_service:
    state: stopped
    name: authelia-main

- name: Get vault access ids from sops
  community.sops.load_vars:
    file: "../secrets.yaml"
    name: secrets
  delegate_to: localhost

- name: Login to vault
  community.hashi_vault.vault_login:
    url: https://vault.home
    auth_method: approle
    role_id: "{{ secrets.vault_role_id }}"
    secret_id: "{{ secrets.vault_secret_id }}"
  register: res
  delegate_to: localhost

- name: Retrieve DB credentials from vault
  community.hashi_vault.vault_kv2_get:
    url: https://vault.home
    token: '{{ res | community.hashi_vault.vault_login_token }}'
    engine_mount_point: kv
    auth_method: token
    path: authelia-creds
  register: vault
  delegate_to: localhost

- ansible.builtin.set_fact:
    jwt: "{{ vault.secret.jwt }}"
    storage_key: "{{ vault.secret.storage_key }}"
    user_password_hash: "{{ vault.secret.user_password_hash }}"
    session_secret: "{{ vault.secret.session_secret }}"
  
- name: Create needed dir
  ansible.builtin.file:
    path: "/etc/authelia"
    owner: "authelia-main"
    group: "authelia-main"
    state: "directory"

- name: Copy needed files for authelia to function
  ansible.builtin.template:
    src: "./{{ item }}.j2"
    dest: "/etc/authelia/{{ item }}"
    owner: "authelia-main"
    group: "authelia-main"
    mode: "0400"
  with_items:
    - config.yaml
    - users_database.yaml

- name: Start services
  ansible.builtin.systemd_service:
    state: started
    name: authelia-main
